// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a0eb38fa-95dd-4552-bf70-4d6e30b7278e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0I1liGfSc",
    "aws_user_pools_web_client_id": "1hndvc8cs0dmgslu9arm92ddpf",
    "oauth": {}
};


export default awsmobile;
